"""Isolated execution of LLM-generated analysis code.

The generated code never runs inside the agent process. It is written to disk,
wrapped in a fixed harness and executed in a fresh interpreter with a timeout,
so a syntax error, an infinite loop or a crash costs one subprocess -- not the
whole graph. The stderr that comes back is exactly what the repair loop feeds
to the LLM Integration node.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

HARNESS = '''# --- auto-generated by the agent; do not edit ------------------------------
import json, sys, traceback
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

pd.set_option("display.width", 140)
pd.set_option("display.max_columns", 60)

RUN_DIR = Path(r"{run_dir}")
FIG_DIR = RUN_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

df = pd.read_pickle(r"{clean_path}")
RESULTS = {{}}
FIGURES = []


def save_fig(name):
    """Persist the current matplotlib figure and register it in the report."""
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in str(name))
    path = FIG_DIR / f"{{safe}}.png"
    plt.tight_layout()
    plt.savefig(path, dpi=140, bbox_inches="tight")
    plt.close()
    FIGURES.append(str(path))
    return str(path)


_status, _error = "ok", ""
try:
# --- BEGIN GENERATED ANALYSIS ---------------------------------------------
{code}
# --- END GENERATED ANALYSIS -----------------------------------------------
except Exception:
    _status, _error = "error", traceback.format_exc()
    print(_error, file=sys.stderr)

# Safety net: models routinely compute the right aggregates and then forget to
# assign them into RESULTS. Rather than lose the work, adopt any DataFrame,
# Series or scalar the analysis left in the namespace.
if not RESULTS:
    _reserved = {{
        "df", "pd", "np", "plt", "matplotlib", "json", "sys", "traceback", "Path",
        "RESULTS", "FIGURES", "save_fig", "RUN_DIR", "FIG_DIR",
    }}
    for _name, _value in list(globals().items()):
        if _name.startswith("_") or _name in _reserved:
            continue
        if isinstance(_value, (pd.DataFrame, pd.Series, int, float, np.number)) and not callable(_value):
            RESULTS[_name] = _value
    if RESULTS:
        print(f"[harness] auto-captured {{len(RESULTS)}} unassigned result(s): "
              f"{{', '.join(RESULTS)}}", file=sys.stderr)


def _jsonable(value, _depth=0):
    if _depth > 4:
        return str(value)
    if isinstance(value, (str, bool, int)) or value is None:
        return value
    if isinstance(value, float):
        return None if (value != value or value in (float("inf"), float("-inf"))) else round(value, 6)
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return _jsonable(float(value), _depth)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, pd.DataFrame):
        return {{"__table__": value.head(50).round(4).to_dict(orient="records"),
                "__columns__": [str(c) for c in value.columns],
                "__shape__": list(value.shape)}}
    if isinstance(value, pd.Series):
        return {{"__series__": {{str(k): _jsonable(v, _depth + 1) for k, v in value.head(50).items()}}}}
    if isinstance(value, np.ndarray):
        return _jsonable(value.tolist(), _depth + 1)
    if isinstance(value, dict):
        return {{str(k): _jsonable(v, _depth + 1) for k, v in value.items()}}
    if isinstance(value, (list, tuple, set)):
        return [_jsonable(v, _depth + 1) for v in list(value)[:200]]
    return str(value)


payload = {{
    "status": _status,
    "error": _error,
    "results": {{str(k): _jsonable(v) for k, v in RESULTS.items()}},
    "figures": FIGURES,
}}
(RUN_DIR / "result.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
sys.exit(1 if _status == "error" else 0)
'''

# Patterns that must never appear in generated analysis code.
_FORBIDDEN = [
    (r"\bimport\s+(os|subprocess|shutil|socket|requests|urllib|httpx|pickle|ctypes)\b", "system/network import"),
    (r"\bfrom\s+(os|subprocess|shutil|socket|requests|urllib|httpx|ctypes)\b", "system/network import"),
    (r"\b__import__\s*\(", "__import__"),
    (r"\beval\s*\(", "eval()"),
    (r"\bexec\s*\(", "exec()"),
    (r"\bopen\s*\([^)]*['\"][wax]", "file write via open()"),
    (r"\.to_(csv|parquet|excel|sql)\s*\(", "writing datasets to disk"),
    (r"\bsys\s*\.\s*exit\b", "sys.exit"),
]


@dataclass
class ExecResult:
    ok: bool
    stdout: str = ""
    stderr: str = ""
    results: dict = field(default_factory=dict)
    figures: list[str] = field(default_factory=list)
    script_path: str = ""


def check_code(code: str) -> str | None:
    """Return a reason string if the code is disallowed, else None."""
    for pattern, reason in _FORBIDDEN:
        if re.search(pattern, code):
            return f"Blocked: generated code uses {reason}."
    return None


def _indent(code: str) -> str:
    return "\n".join(("    " + line) if line.strip() else "" for line in code.splitlines())


def run_analysis(code: str, *, run_dir: str | Path, clean_path: str | Path, timeout: int = 120,
                 attempt: int = 1) -> ExecResult:
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    violation = check_code(code)
    if violation:
        return ExecResult(ok=False, stderr=violation)

    script = HARNESS.format(run_dir=str(run_dir), clean_path=str(clean_path), code=_indent(code))
    script_path = run_dir / f"analysis_attempt_{attempt}.py"
    script_path.write_text(script, encoding="utf-8")

    result_file = run_dir / "result.json"
    if result_file.exists():
        result_file.unlink()

    try:
        proc = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=str(run_dir),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        stdout, stderr, code_rc = proc.stdout, proc.stderr, proc.returncode
    except subprocess.TimeoutExpired:
        return ExecResult(
            ok=False,
            stderr=f"TimeoutError: analysis exceeded {timeout}s. Use a vectorised approach.",
            script_path=str(script_path),
        )

    payload = {}
    if result_file.exists():
        try:
            payload = json.loads(result_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass

    ok = code_rc == 0 and payload.get("status") == "ok"
    return ExecResult(
        ok=ok,
        stdout=stdout[-8000:],
        stderr=(payload.get("error") or stderr)[-6000:],
        results=payload.get("results", {}),
        figures=payload.get("figures", []),
        script_path=str(script_path),
    )
